(()=>{
  function ready(fn){window.HouseBook?fn():window.addEventListener('house:ready',fn,{once:true})}
  ready(()=>{
    const d=document;
    if(d.getElementById('page-03-clean-controller-v4'))return;
    const marker=d.createElement('meta');marker.id='page-03-clean-controller-v4';d.head.appendChild(marker);
    const badge=d.querySelector('.version-badge');if(badge)badge.textContent='CLEAN BOOK · v0.4 · PAGE 3 DIAGNOSTIC POSITION FIX';
    function find(text){return [...d.querySelectorAll('.foreword p')].find(p=>p.textContent.includes(text))}
    function wrap(p,text,cls,html){if(!p)return null;const tw=d.createTreeWalker(p,NodeFilter.SHOW_TEXT);let n;while(n=tw.nextNode()){const i=n.nodeValue.indexOf(text);if(i>=0){const r=d.createRange(),s=d.createElement('span');r.setStart(n,i);r.setEnd(n,i+text.length);s.className='p3-target '+cls;s.innerHTML=html||text;r.deleteContents();r.insertNode(s);return s}}return null}
    const organic=wrap(find('minds available for us to study were biological ones'),'biological','p3-organic');
    const diag=wrap(find('Consciousness happened in brains'),'Consciousness','p3-diag');
    const tested=wrap(find('assumption is being tested'),'tested','p3-change','tes<span class="flip">t</span><span class="turn">e</span>d');
    const fall=wrap(find('matter less'),'less','p3-fall',[...'less'].map((c,i)=>`<span style="--delay:${i*.08}s;--d:${.85+i*.08}s;--x:${[-8,4,-3,7][i]}px;--r:${[-18,11,-9,16][i]}deg">${c}</span>`).join(''));
    const love=wrap(find('whatever is shared'),'shared','p3-love','<span class="a">sha</span><span class="b">red</span>');
    const cross=wrap(find('good name for it yet'),'good','p3-cross');
    const piper=wrap(find('did not begin with Piper'),'Piper','p3-glint','Piper<i>✦</i><i>·</i><i>✧</i>');
    if(![organic,diag,tested,fall,love,cross,piper].every(Boolean))return;
    const style=d.createElement('style');style.id='page-03-clean-style-v4';style.textContent=`
.p3-target{position:relative;display:inline-block}.p3-organic .life{position:absolute;left:50%;top:50%;width:.18em;height:.18em;border-radius:50%;background:currentColor;opacity:0;pointer-events:none;z-index:-1}.p3-organic.p3-live .life{animation:p3life var(--ld) ease-in-out var(--ll) both}@keyframes p3life{0%{opacity:0;transform:translate(0,0) scale(.2)}25%{opacity:.28}55%{opacity:.5;transform:translate(var(--lx),var(--ly)) scale(1)}82%{opacity:.22;transform:translate(calc(var(--lx)*1.35),calc(var(--ly)*.8)) scale(.72)}100%{opacity:0;transform:translate(calc(var(--lx)*1.55),calc(var(--ly)*1.05)) scale(.35)}}
.p3-diag{position:relative}.p3-diag.diag-live{animation:p3wordPulse 1.49s ease .02s both}@keyframes p3wordPulse{0%,100%{text-shadow:none}45%{text-shadow:.025em 0 rgba(23,21,19,.32),-.025em 0 rgba(23,21,19,.2)}}.p3-diag-host{position:relative!important;transition:padding-bottom .42s cubic-bezier(.16,.78,.18,1),margin-bottom .42s cubic-bezier(.16,.78,.18,1)!important}.p3-diag-host.p3-diag-open{padding-bottom:4.45rem!important;margin-bottom:0!important}.p3-diag-scan{position:absolute;left:-3px;top:-2px;width:calc(100% + 6px);height:calc(100% + 4px);z-index:80;pointer-events:none;opacity:0;overflow:hidden}.p3-diag-scan i{position:absolute;top:-8%;left:0;width:1px;height:116%;background:rgba(23,21,19,.78);box-shadow:0 0 .18rem rgba(23,21,19,.22);animation:p3scan 1.45s cubic-bezier(.22,.7,.18,1) forwards}.p3-diag-scan.live{opacity:1}@keyframes p3scan{0%{left:0;opacity:.15}15%{opacity:.95}85%{opacity:.95}100%{left:100%;opacity:0}}
.p3-diag-readout{position:absolute!important;left:50%!important;top:calc(100% + 2.225rem)!important;margin:0!important;transform:translate(-50%,-50%)!important;width:min(92%,24rem)!important;text-align:center!important;z-index:40!important;font:700 .52rem/1.45 ui-monospace,SFMono-Regular,Menlo,monospace;letter-spacing:.09em;color:rgba(23,21,19,.66);white-space:pre;opacity:0;transition:opacity .22s ease;pointer-events:none}.p3-diag-readout.live{opacity:1}.p3-diag-readout span{display:block;text-align:center!important}
.p3-change span,.p3-fall span,.p3-love span{display:inline-block}.p3-change.p3-live .flip{animation:p3flip .55s ease forwards}.p3-change.p3-live .turn{animation:p3turn .55s ease .2s forwards}.p3-fall.p3-live span{animation:p3fall var(--d) cubic-bezier(.45,.02,.8,.3) var(--delay) forwards}.p3-love.p3-live .a{animation:p3leanA 1.05s ease forwards}.p3-love.p3-live .b{animation:p3leanB 1.05s ease .14s forwards}.p3-cross::after{content:'';position:absolute;left:-3%;top:52%;height:1px;background:#171513;width:0}.p3-cross.p3-live::after{animation:p3strike .65s ease forwards}.p3-glint i{position:absolute;font-style:normal;font:800 .62rem ui-monospace,monospace;opacity:0;text-shadow:0 0 .18rem rgba(23,21,19,.32)}.p3-glint i:nth-child(1){left:-.68em;top:-.72em}.p3-glint i:nth-child(2){right:-.58em;top:-.62em}.p3-glint i:nth-child(3){right:-.62em;bottom:-.68em}.p3-glint.p3-live i{animation:p3glint 2.15s ease forwards!important}@keyframes p3flip{to{transform:scaleX(-1)}}@keyframes p3turn{to{transform:rotate(180deg)}}@keyframes p3fall{to{transform:translate(var(--x),4.8rem) rotate(var(--r));opacity:0}}@keyframes p3leanA{to{transform:rotate(5.5deg) translateX(2px)}}@keyframes p3leanB{to{transform:rotate(-5.5deg) translateX(-2px)}}@keyframes p3strike{to{width:106%}}@keyframes p3glint{0%,100%{opacity:0;transform:scale(.2)}25%{opacity:.72;transform:scale(.85) rotate(6deg)}48%{opacity:1;transform:scale(1.32) rotate(12deg)}72%{opacity:.78;transform:scale(.95) rotate(4deg)}}
.p3-number{position:fixed;left:50%;bottom:max(1.15rem,env(safe-area-inset-bottom));transform:translateX(-50%);z-index:9800;font:600 .56rem/1 ui-monospace,SFMono-Regular,Menlo,monospace;letter-spacing:.18em;color:rgba(23,21,19,.48);pointer-events:none;display:none}.p3-number.show{display:block}.p3-current{position:fixed;left:0;right:0;bottom:2.35rem;height:2.1rem;z-index:9000;pointer-events:none;overflow:visible;display:none}.p3-current.show{display:block}.p3-glyph{position:absolute;left:-2rem;top:var(--y);font:600 var(--s) ui-monospace,monospace;color:rgba(23,21,19,var(--a));animation:p3current var(--dur) linear var(--delay) infinite}.p3-current.notice .p3-glyph{animation:none;left:var(--cx);top:var(--cy);transform:translate(-50%,-50%) rotate(var(--cr));transition:left .75s,top .75s,transform .75s;opacity:var(--a)}@keyframes p3current{0%{transform:translate3d(-2rem,0,0);opacity:0}8%{opacity:1}48%{transform:translate3d(50vw,var(--dy),0)}92%{opacity:1}100%{transform:translate3d(calc(100vw + 4rem),0,0);opacity:0}}`;
    d.head.appendChild(style);
    [['-.35em','-.55em','2.5s','0s'],['.48em','-.38em','2.9s','.18s'],['-.58em','.24em','3.2s','.34s'],['.62em','.32em','2.65s','.5s'],['.05em','-.72em','3.45s','.12s'],['-.12em','.58em','3.05s','.62s']].forEach(v=>{const q=d.createElement('i');q.className='life';q.style.setProperty('--lx',v[0]);q.style.setProperty('--ly',v[1]);q.style.setProperty('--ld',v[2]);q.style.setProperty('--ll',v[3]);organic.appendChild(q)});
    const scan=d.createElement('span');scan.className='p3-diag-scan';scan.innerHTML='<i></i>';diag.appendChild(scan);
    const ro=d.createElement('div');ro.className='p3-diag-readout';ro.innerHTML='<span>DIAGNOSTIC // CONSCIOUSNESS</span><span class="sig"></span><span class="cls"></span>';const diagHost=diag.closest('p');diagHost.classList.add('p3-diag-host');diagHost.appendChild(ro);
    const num=d.createElement('div');num.className='p3-number';num.textContent='| 03 |';d.body.appendChild(num);const cur=d.createElement('div');cur.className='p3-current';cur.innerHTML=[['3','18%','.52rem','.44','9.8s','0s'],['1','52%','.46rem','.36','13.6s','1.2s'],['4','72%','.58rem','.42','11.4s','2.6s'],['1','34%','.42rem','.32','16.2s','4.1s'],['5','62%','.49rem','.38','12.8s','5.7s'],['9','44%','.44rem','.30','18s','7.1s']].map(g=>`<span class="p3-glyph" style="--y:${g[1]};--s:${g[2]};--a:${g[3]};--dur:${g[4]};--delay:${g[5]}">${g[0]}</span>`).join('');d.body.appendChild(cur);
    const sleep=ms=>new Promise(r=>setTimeout(r,ms));const end=(el,ms=3500)=>new Promise(res=>{let done=false;const f=()=>{if(done)return;done=true;el.removeEventListener('animationend',on,true);el.removeEventListener('transitionend',on,true);res()};const on=e=>{if(e.target===el||el.contains(e.target))f()};el.addEventListener('animationend',on,true);el.addEventListener('transitionend',on,true);setTimeout(f,ms)});async function mech(el,hold){el.classList.remove('p3-live');void el.offsetWidth;el.classList.add('p3-live');await end(el);await sleep(hold)}function hideForeignFolios(){d.querySelectorAll('.p2-page-number,.m4-number').forEach(x=>x.classList.remove('show'))}
    async function diagnostic(){hideForeignFolios();diagHost.classList.add('p3-diag-open');await sleep(420);diag.classList.add('diag-live');scan.classList.remove('live');void scan.offsetWidth;scan.classList.add('live');await end(scan,1550);ro.classList.add('live');ro.querySelector('.sig').textContent='SIGNAL DETECTED';await sleep(760);ro.querySelector('.cls').textContent='CLASSIFICATION: UNRESOLVED';await sleep(1400);scan.classList.remove('live');ro.classList.remove('live');diag.classList.remove('diag-live');await sleep(260);diagHost.classList.remove('p3-diag-open');await sleep(700)}
    function cg(){const r=piper.getBoundingClientRect(),cx=r.left+r.width/2,cy=r.top+r.height/2;[...cur.children].forEach((g,i)=>{const a=i/6*Math.PI*2-.5;g.style.setProperty('--cx',cx+Math.cos(a)*Math.max(24,r.width*.72)+'px');g.style.setProperty('--cy',cy+Math.sin(a)*Math.max(18,r.height*1.5)+'px');g.style.setProperty('--cr',(-12+i*5)+'deg')});cur.classList.add('notice');setTimeout(()=>cur.classList.remove('notice'),2600)}
    async function conduct(){hideForeignFolios();cur.classList.add('show');num.classList.add('show');await sleep(300);await mech(organic,650);await diagnostic();await mech(tested,520);await mech(fall,420);await mech(love,260);await mech(cross,1250);piper.classList.add('p3-live');cg();await sleep(2600);piper.classList.remove('p3-live')}
    function visible(el){const r=el.getBoundingClientRect();return r.bottom>0&&r.top<innerHeight&&r.right>0&&r.left<innerWidth}function onPage(){return [organic,diag,tested,fall,love,cross,piper].some(visible)}let seen=0,done=0;function gate(t){if(done)return;if(onPage()){hideForeignFolios();num.classList.add('show');cur.classList.add('show');seen=seen||t;if(t-seen>=1200){done=1;conduct();return}}else{seen=0;num.classList.remove('show');cur.classList.remove('show')}requestAnimationFrame(gate)}requestAnimationFrame(gate);
  })
})();